const comment = { awarders: [],
    total_awards_received: 0,
    approved_at_utc: null,
    link_title: 'Who averages the most High Fives per game?',
    mod_reason_by: null,
    banned_by: null,
    author_flair_type: 'text',
    removal_reason: null,
    link_id: 't3_dgr4io',
    author_flair_template_id: null,
    likes: null,
    replies: Listing[],
    user_reports: [],
    saved: false,
    id: 'f3e64ju',
    banned_at_utc: null,
    mod_reason_title: null,
    gilded: 0,
    archived: false,
    no_follow: true,
    author: RedditUser { name: 'idontknowanythingnba' },
    num_comments: 2,
    can_mod_post: false,
    created_utc: 1570859450,
    send_replies: true,
    parent_id: 't3_dgr4io',
    score: 1,
    author_fullname: 't2_4ivfkzqn',
    over_18: false,
    approved_by: null,
    mod_note: null,
    all_awardings: [],
    subreddit_id: 't5_2qo4s',
    body: 'if were going team then definitely celtics',
    edited: false,
    author_flair_css_class: null,
    name: 't1_f3e64ju',
    steward_reports: [],
    author_patreon_flair: false,
    downs: 0,
    author_flair_richtext: [],
    is_submitter: false,
    body_html:
     '<div class="md"><p>if were going team then definitely celtics</p>\n</div>',
    gildings: {},
    collapsed_reason: null,
    distinguished: null,
    associated_award: null,
    stickied: false,
    can_gild: true,
    subreddit: Subreddit { display_name: 'nba' },
    author_flair_text_color: null,
    score_hidden: true,
    permalink:
     '/r/nba/comments/dgr4io/who_averages_the_most_high_fives_per_game/f3e64ju/',
    num_reports: null,
    link_permalink:
     'https://www.reddit.com/r/nba/comments/dgr4io/who_averages_the_most_high_fives_per_game/',
    report_reasons: null,
    link_author: 'Dakooder',
    author_flair_text: null,
    link_url:
     'https://www.reddit.com/r/nba/comments/dgr4io/who_averages_the_most_high_fives_per_game/',
    created: 1570888250,
    collapsed: false,
    subreddit_name_prefixed: 'r/nba',
    controversiality: 0,
    locked: false,
    author_flair_background_color: null,
    mod_reports: [],
    quarantine: false,
    subreddit_type: 'public',
    ups: 1 
};